services:
  pgdatabase:
    image: postgres:13
    environment:
      - name=pg-database
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ~/Data_Engineering_Zoomcamp/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=tom@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80